apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slave
  name: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slave
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: slave-1
    spec:
      containers:
        - env:
            - name: KAFKAADDR
              value: broker
            - name: KAFKAGROUP
              value: solvers
            - name: KAFKAOFTRST
              value: earliest
            - name: KAFKAPORT
              value: "9092"
            - name: MINSUPPORT
              value: "500"
            - name: MONGOADDR
              value: mongodb
            - name: MONGOPASS
              value: root
            - name: MONGOPORT
              value: "27017"
            - name: MONGOUSER
              value: root
            - name: NCORES
              value: "2"
          image: servant
          name: solver1
          resources: {}
      restartPolicy: Always
status: {}
