apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slave
  name: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: slave
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: slave
    spec:
      containers:
        - env:
            - name: KAFKAADDR
              value: broker.dvrc.svc.cluster.local
            - name: KAFKAGROUP
              value: solvers
            - name: KAFKAOFTRST
              value: earliest
            - name: KAFKAPORT
              value: "29092"
            - name: MINSUPPORT
              value: "500"
            - name: MONGOADDR
              value: mongodb
            - name: MONGOPASS
              value: root
            - name: MONGOPORT
              value: "27017"
            - name: MONGOUSER
              value: root
            - name: NCORES
              value: "1"
          image: s3.dvic.devinci.fr/clusterspeed/slave:latest
          name: solver
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: OnFailure
status: {}
