FROM flexiboy/core

ENV MINSUPPORT=500
ENV NCORES=2

WORKDIR /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/

ADD ./code/servant ./code/servant
ADD ./data ./data

RUN cd code/servant/core \
	&& make clean\
	&& make -k CXX=g++-10

WORKDIR /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/servant/core

CMD ./slave -minSupport=${MINSUPPORT} -ncores=${NCORES}
