---
version: '3.8'

services: 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on: 
      - zookeeper
    ports: 
      - "29092:29092"
    environment: 
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #KAFKA_LISTENERS: PLAINTEXT://broker:9092, PLAINTEXT_HOST://localhost:29092 #For more complex network systems
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT #For more complex network systems
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on: 
      - broker
    ports: 
      - "8081:8081"
    environment: 
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:9092'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN

  mongodb:
    image: mongo
    container_name: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - /Users/Flexiboy/Desktop/Courses/Distributed_SAT_Approach/data/db
    ports: 
      - 27017:27017
    restart: always
  
  mongoAdmin:
    image: mongo-express
    container_name: mongoAdmin
    depends_on: 
      - mongodb
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      VCAP_APP_PORT: 8082
    ports: 
      - 8082:8082
    restart: always

  # master:
  #   image: master
  #   container_name: master
  #   depends_on: 
  #     - mongodb
  #     - broker
  #     - schema-registry
  #   environment: 
  #     - MINSUPPORT=500
  #     - NSOLVERS=2
  #     - RESET=0
  #     - DATASET=../../../data/retail.dat
  #     - MONGOUSER=root
  #     - MONGOPASS=root
  #     - MONGOADDR=mongodb
  #     - MONGOPORT=27017
  #     - KAFKAADDR=broker
  #     - KAFKAPORT=9092
  
  # slave-1:
  #   image: servant
  #   container_name: solver1
  #   depends_on: 
  #     - master
  #   environment: 
  #     - MINSUPPORT=500
  #     - NCORES=2
  #     - MONGOUSER=root
  #     - MONGOPASS=root
  #     - MONGOADDR=mongodb
  #     - MONGOPORT=27017
  #     - KAFKAADDR=broker
  #     - KAFKAPORT=9092
  #     - KAFKAGROUP=solvers
  #     - KAFKAOFTRST=earliest

  # slave-2:
  #   image: servant
  #   container_name: solver2
  #   depends_on: 
  #     - master
  #   environment: 
  #     - MINSUPPORT=500
  #     - NCORES=2
  #     - MONGOUSER=root
  #     - MONGOPASS=root
  #     - MONGOADDR=mongodb
  #     - MONGOPORT=27017
  #     - KAFKAADDR=broker
  #     - KAFKAPORT=9092
  #     - KAFKAGROUP=solvers
  #     - KAFKAOFTRST=earliest
