FROM ubuntu:20.10

RUN apt-get update -y\
	&& apt-get upgrade -y\
	&& apt-get install build-essential -y\
	&& apt-get install manpages-dev -y\
	&& apt-get install software-properties-common -y\
	&& add-apt-repository ppa:ubuntu-toolchain-r/test\
	&& apt-get update -y\
	&& apt-get upgrade -y\
	&& apt-get install libz-dev -y\
	&& apt-get install gcc -y\
	&& apt-get install g++-10 -y\
	&& apt-get install cmake -y\
	&& apt-get install librdkafka-dev -y\
	&& apt-get install libboost-all-dev -y\
	&& apt-get install openssl -y\
	&& apt-get install libssl-dev -y\
	&& apt-get install libsasl2-dev -y\
	&& apt-get install openjdk-8-jre -y\
	&& apt-get install gradle -y\
	&& apt-get install libbson-1.0-0 -y\
	&& apt-get install libmongoc-1.0-0 -y\
	&& apt-get clean -y

CMD /usr/bin/bash
