/Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Cooperation.o /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Cooperation.or /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Cooperation.od /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Cooperation.op: \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Cooperation.cc \
 ../core/Cooperation.h ../core/SolverTypes.h ../core/../mtl/IntTypes.h \
 ../core/../mtl/Alg.h ../core/../mtl/Vec.h ../core/../mtl/IntTypes.h \
 ../core/../mtl/XAlloc.h ../core/../mtl/Vec.h ../core/../mtl/Map.h \
 ../core/../mtl/Alloc.h ../core/Solver.h ../core/../mtl/Heap.h \
 ../core/../utils/Options.h ../core/../utils/../mtl/IntTypes.h \
 ../core/../utils/../mtl/Vec.h ../core/../utils/ParseUtils.h \
 ../mtl/Sort.h ../mtl/Vec.h
/Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Main.o /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Main.or /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Main.od /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Main.op: \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Main.cc \
 /usr/local/include/omp.h /usr/local/include/librdkafka/rdkafka.h \
 /usr/local/include/cppkafka/cppkafka.h \
 /usr/local/include/cppkafka/buffer.h \
 /usr/local/include/cppkafka/macros.h \
 /usr/local/include/cppkafka/exceptions.h \
 /usr/local/include/cppkafka/error.h \
 /usr/local/include/cppkafka/clonable_ptr.h \
 /usr/local/include/cppkafka/configuration.h \
 /usr/local/include/boost/optional.hpp \
 /usr/local/include/boost/optional/optional.hpp \
 /usr/local/include/boost/assert.hpp \
 /usr/local/include/boost/core/addressof.hpp \
 /usr/local/include/boost/config.hpp \
 /usr/local/include/boost/config/user.hpp \
 /usr/local/include/boost/config/detail/select_compiler_config.hpp \
 /usr/local/include/boost/config/compiler/gcc.hpp \
 /usr/local/include/boost/config/detail/select_stdlib_config.hpp \
 /usr/local/include/boost/config/stdlib/libstdcpp3.hpp \
 /usr/local/include/boost/config/detail/select_platform_config.hpp \
 /usr/local/include/boost/config/platform/macos.hpp \
 /usr/local/include/boost/config/detail/posix_features.hpp \
 /usr/local/include/boost/config/detail/suffix.hpp \
 /usr/local/include/boost/core/enable_if.hpp \
 /usr/local/include/boost/core/explicit_operator_bool.hpp \
 /usr/local/include/boost/config/workaround.hpp \
 /usr/local/include/boost/core/swap.hpp \
 /usr/local/include/boost/optional/bad_optional_access.hpp \
 /usr/local/include/boost/static_assert.hpp \
 /usr/local/include/boost/detail/workaround.hpp \
 /usr/local/include/boost/throw_exception.hpp \
 /usr/local/include/boost/exception/exception.hpp \
 /usr/local/include/boost/assert/source_location.hpp \
 /usr/local/include/boost/current_function.hpp \
 /usr/local/include/boost/cstdint.hpp /usr/local/include/boost/type.hpp \
 /usr/local/include/boost/type_traits/alignment_of.hpp \
 /usr/local/include/boost/type_traits/intrinsics.hpp \
 /usr/local/include/boost/type_traits/detail/config.hpp \
 /usr/local/include/boost/version.hpp \
 /usr/local/include/boost/type_traits/integral_constant.hpp \
 /usr/local/include/boost/type_traits/conditional.hpp \
 /usr/local/include/boost/type_traits/has_nothrow_constructor.hpp \
 /usr/local/include/boost/type_traits/is_default_constructible.hpp \
 /usr/local/include/boost/type_traits/is_complete.hpp \
 /usr/local/include/boost/type_traits/declval.hpp \
 /usr/local/include/boost/type_traits/add_rvalue_reference.hpp \
 /usr/local/include/boost/type_traits/is_void.hpp \
 /usr/local/include/boost/type_traits/is_reference.hpp \
 /usr/local/include/boost/type_traits/is_lvalue_reference.hpp \
 /usr/local/include/boost/type_traits/is_rvalue_reference.hpp \
 /usr/local/include/boost/type_traits/remove_reference.hpp \
 /usr/local/include/boost/type_traits/is_function.hpp \
 /usr/local/include/boost/type_traits/detail/is_function_cxx_11.hpp \
 /usr/local/include/boost/type_traits/detail/yes_no_type.hpp \
 /usr/local/include/boost/type_traits/type_with_alignment.hpp \
 /usr/local/include/boost/type_traits/is_pod.hpp \
 /usr/local/include/boost/type_traits/is_scalar.hpp \
 /usr/local/include/boost/type_traits/is_arithmetic.hpp \
 /usr/local/include/boost/type_traits/is_integral.hpp \
 /usr/local/include/boost/type_traits/is_floating_point.hpp \
 /usr/local/include/boost/type_traits/is_enum.hpp \
 /usr/local/include/boost/type_traits/is_pointer.hpp \
 /usr/local/include/boost/type_traits/is_member_pointer.hpp \
 /usr/local/include/boost/type_traits/is_member_function_pointer.hpp \
 /usr/local/include/boost/type_traits/detail/is_member_function_pointer_cxx_11.hpp \
 /usr/local/include/boost/type_traits/remove_const.hpp \
 /usr/local/include/boost/type_traits/decay.hpp \
 /usr/local/include/boost/type_traits/is_array.hpp \
 /usr/local/include/boost/type_traits/remove_bounds.hpp \
 /usr/local/include/boost/type_traits/remove_extent.hpp \
 /usr/local/include/boost/type_traits/add_pointer.hpp \
 /usr/local/include/boost/type_traits/remove_cv.hpp \
 /usr/local/include/boost/type_traits/is_base_of.hpp \
 /usr/local/include/boost/type_traits/is_base_and_derived.hpp \
 /usr/local/include/boost/type_traits/is_same.hpp \
 /usr/local/include/boost/type_traits/is_class.hpp \
 /usr/local/include/boost/type_traits/is_const.hpp \
 /usr/local/include/boost/type_traits/is_constructible.hpp \
 /usr/local/include/boost/type_traits/is_destructible.hpp \
 /usr/local/include/boost/type_traits/is_nothrow_move_assignable.hpp \
 /usr/local/include/boost/type_traits/has_trivial_move_assign.hpp \
 /usr/local/include/boost/type_traits/is_assignable.hpp \
 /usr/local/include/boost/type_traits/is_volatile.hpp \
 /usr/local/include/boost/type_traits/has_nothrow_assign.hpp \
 /usr/local/include/boost/type_traits/enable_if.hpp \
 /usr/local/include/boost/type_traits/is_nothrow_move_constructible.hpp \
 /usr/local/include/boost/move/utility.hpp \
 /usr/local/include/boost/move/detail/config_begin.hpp \
 /usr/local/include/boost/move/detail/workaround.hpp \
 /usr/local/include/boost/move/utility_core.hpp \
 /usr/local/include/boost/move/core.hpp \
 /usr/local/include/boost/move/detail/config_end.hpp \
 /usr/local/include/boost/move/detail/meta_utils.hpp \
 /usr/local/include/boost/move/detail/meta_utils_core.hpp \
 /usr/local/include/boost/move/traits.hpp \
 /usr/local/include/boost/move/detail/type_traits.hpp \
 /usr/local/include/boost/none.hpp /usr/local/include/boost/none_t.hpp \
 /usr/local/include/boost/utility/compare_pointees.hpp \
 /usr/local/include/boost/utility/result_of.hpp \
 /usr/local/include/boost/preprocessor/cat.hpp \
 /usr/local/include/boost/preprocessor/config/config.hpp \
 /usr/local/include/boost/preprocessor/iteration/iterate.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/dec.hpp \
 /usr/local/include/boost/preprocessor/config/limits.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/limits/dec_256.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/inc.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/limits/inc_256.hpp \
 /usr/local/include/boost/preprocessor/array/elem.hpp \
 /usr/local/include/boost/preprocessor/array/data.hpp \
 /usr/local/include/boost/preprocessor/tuple/elem.hpp \
 /usr/local/include/boost/preprocessor/facilities/expand.hpp \
 /usr/local/include/boost/preprocessor/facilities/overload.hpp \
 /usr/local/include/boost/preprocessor/variadic/size.hpp \
 /usr/local/include/boost/preprocessor/control/iif.hpp \
 /usr/local/include/boost/preprocessor/facilities/check_empty.hpp \
 /usr/local/include/boost/preprocessor/variadic/has_opt.hpp \
 /usr/local/include/boost/preprocessor/variadic/limits/size_64.hpp \
 /usr/local/include/boost/preprocessor/tuple/rem.hpp \
 /usr/local/include/boost/preprocessor/tuple/detail/is_single_return.hpp \
 /usr/local/include/boost/preprocessor/variadic/elem.hpp \
 /usr/local/include/boost/preprocessor/variadic/limits/elem_64.hpp \
 /usr/local/include/boost/preprocessor/array/size.hpp \
 /usr/local/include/boost/preprocessor/slot/slot.hpp \
 /usr/local/include/boost/preprocessor/slot/detail/def.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_params.hpp \
 /usr/local/include/boost/preprocessor/punctuation/comma_if.hpp \
 /usr/local/include/boost/preprocessor/control/if.hpp \
 /usr/local/include/boost/preprocessor/logical/bool.hpp \
 /usr/local/include/boost/preprocessor/logical/limits/bool_256.hpp \
 /usr/local/include/boost/preprocessor/facilities/empty.hpp \
 /usr/local/include/boost/preprocessor/punctuation/comma.hpp \
 /usr/local/include/boost/preprocessor/repetition/repeat.hpp \
 /usr/local/include/boost/preprocessor/debug/error.hpp \
 /usr/local/include/boost/preprocessor/detail/auto_rec.hpp \
 /usr/local/include/boost/preprocessor/detail/limits/auto_rec_256.hpp \
 /usr/local/include/boost/preprocessor/tuple/eat.hpp \
 /usr/local/include/boost/preprocessor/repetition/limits/repeat_256.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_trailing_params.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_binary_params.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_shifted_params.hpp \
 /usr/local/include/boost/preprocessor/facilities/intercept.hpp \
 /usr/local/include/boost/preprocessor/facilities/limits/intercept_256.hpp \
 /usr/local/include/boost/type_traits/type_identity.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/iter/forward1.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/bounds/lower1.hpp \
 /usr/local/include/boost/preprocessor/slot/detail/shared.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/bounds/upper1.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/iter/limits/forward1_256.hpp \
 /usr/local/include/boost/utility/detail/result_of_iterate.hpp \
 /usr/local/include/boost/optional/optional_fwd.hpp \
 /usr/local/include/boost/optional/detail/optional_config.hpp \
 /usr/local/include/boost/optional/detail/optional_factory_support.hpp \
 /usr/local/include/boost/optional/detail/optional_aligned_storage.hpp \
 /usr/local/include/boost/optional/detail/optional_trivially_copyable_base.hpp \
 /usr/local/include/boost/optional/detail/optional_reference_spec.hpp \
 /usr/local/include/boost/optional/detail/optional_relops.hpp \
 /usr/local/include/boost/optional/detail/optional_swap.hpp \
 /usr/local/include/cppkafka/topic_partition_list.h \
 /usr/local/include/cppkafka/topic_configuration.h \
 /usr/local/include/cppkafka/clonable_ptr.h \
 /usr/local/include/cppkafka/configuration_base.h \
 /usr/local/include/cppkafka/configuration_option.h \
 /usr/local/include/cppkafka/event.h \
 /usr/local/include/cppkafka/message.h \
 /usr/local/include/cppkafka/buffer.h \
 /usr/local/include/cppkafka/header_list.h \
 /usr/local/include/cppkafka/header.h \
 /usr/local/include/cppkafka/header_list_iterator.h \
 /usr/local/include/cppkafka/message_timestamp.h \
 /usr/local/include/cppkafka/topic_partition.h \
 /usr/local/include/cppkafka/configuration_base.h \
 /usr/local/include/cppkafka/configuration_option.h \
 /usr/local/include/cppkafka/consumer.h \
 /usr/local/include/cppkafka/kafka_handle_base.h \
 /usr/local/include/cppkafka/group_information.h \
 /usr/local/include/cppkafka/metadata.h \
 /usr/local/include/cppkafka/configuration.h \
 /usr/local/include/cppkafka/logging.h \
 /usr/local/include/cppkafka/queue.h \
 /usr/local/include/cppkafka/detail/callback_invoker.h \
 /usr/local/include/cppkafka/detail/../logging.h \
 /usr/local/include/cppkafka/detail/../kafka_handle_base.h \
 /usr/local/include/cppkafka/error.h /usr/local/include/cppkafka/event.h \
 /usr/local/include/cppkafka/exceptions.h \
 /usr/local/include/cppkafka/group_information.h \
 /usr/local/include/cppkafka/header.h \
 /usr/local/include/cppkafka/header_list.h \
 /usr/local/include/cppkafka/header_list_iterator.h \
 /usr/local/include/cppkafka/kafka_handle_base.h \
 /usr/local/include/cppkafka/logging.h \
 /usr/local/include/cppkafka/macros.h \
 /usr/local/include/cppkafka/message.h \
 /usr/local/include/cppkafka/message_builder.h \
 /usr/local/include/cppkafka/topic.h \
 /usr/local/include/cppkafka/message_internal.h \
 /usr/local/include/cppkafka/message_timestamp.h \
 /usr/local/include/cppkafka/metadata.h \
 /usr/local/include/cppkafka/producer.h \
 /usr/local/include/cppkafka/message_builder.h \
 /usr/local/include/cppkafka/queue.h /usr/local/include/cppkafka/topic.h \
 /usr/local/include/cppkafka/topic_configuration.h \
 /usr/local/include/cppkafka/topic_partition.h \
 /usr/local/include/cppkafka/topic_partition_list.h \
 /usr/local/include/cppkafka/utils/backoff_committer.h \
 /usr/local/include/cppkafka/utils/../consumer.h \
 /usr/local/include/cppkafka/utils/backoff_performer.h \
 /usr/local/include/cppkafka/utils/../exceptions.h \
 /usr/local/include/cppkafka/utils/../detail/callback_invoker.h \
 /usr/local/include/cppkafka/utils/../macros.h \
 /usr/local/include/cppkafka/utils/backoff_performer.h \
 /usr/local/include/cppkafka/utils/buffered_producer.h \
 /usr/local/include/cppkafka/utils/../producer.h \
 /usr/local/include/cppkafka/utils/../message_internal.h \
 /usr/local/include/cppkafka/utils/compacted_topic_processor.h \
 /usr/local/include/cppkafka/utils/../buffer.h \
 /usr/local/include/cppkafka/utils/consumer_dispatcher.h \
 /usr/local/include/cppkafka/utils/poll_interface.h \
 /usr/local/include/cppkafka/utils/poll_strategy_base.h \
 /usr/local/include/boost/any.hpp /usr/local/include/boost/type_index.hpp \
 /usr/local/include/boost/type_index/stl_type_index.hpp \
 /usr/local/include/boost/type_index/type_index_facade.hpp \
 /usr/local/include/boost/container_hash/hash_fwd.hpp \
 /usr/local/include/boost/core/demangle.hpp \
 /usr/local/include/boost/type_traits/add_reference.hpp \
 /usr/local/include/boost/utility/enable_if.hpp \
 /usr/local/include/cppkafka/utils/../queue.h \
 /usr/local/include/cppkafka/utils/../event.h \
 /usr/local/include/cppkafka/utils/../macros.h \
 /usr/local/include/cppkafka/utils/../message.h \
 /usr/local/include/cppkafka/utils/../topic_partition_list.h \
 /usr/local/include/cppkafka/utils/poll_interface.h \
 /usr/local/include/cppkafka/utils/roundrobin_poll_strategy.h \
 /usr/local/include/cppkafka/utils/poll_strategy_base.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/System.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/ParseUtils.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/Options.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/../mtl/Vec.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/../mtl/XAlloc.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../utils/ParseUtils.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Dimacs.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Cooperation.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/SolverTypes.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/Alg.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/Vec.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/Vec.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/Map.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/Alloc.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/XAlloc.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Solver.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/../mtl/Heap.h
/Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Solver.o /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Solver.or /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Solver.od /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Solver.op: \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/Solver.cc \
 /usr/local/include/omp.h ../mtl/Sort.h ../mtl/Vec.h ../mtl/IntTypes.h \
 ../mtl/XAlloc.h ../core/Solver.h ../core/../mtl/Vec.h \
 ../core/../mtl/Heap.h ../core/../mtl/Vec.h ../core/../mtl/Alg.h \
 ../core/../utils/Options.h ../core/../utils/../mtl/IntTypes.h \
 ../core/../utils/../mtl/Vec.h ../core/../utils/ParseUtils.h \
 ../core/SolverTypes.h ../core/../mtl/IntTypes.h ../core/../mtl/Map.h \
 ../core/../mtl/IntTypes.h ../core/../mtl/Alloc.h ../core/../mtl/XAlloc.h \
 ../core/Cooperation.h ../core/Solver.h
/Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.o /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.or /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.od /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.op: \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.cc \
 /usr/local/include/librdkafka/rdkafka.h \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/common.h
/Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.o /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.or /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.od /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.op: \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.cc \
 /Users/Flexiboy/Desktop/Projects/Distributed_SAT_Approach_FIM/code/master/core/json.h
