/Users/Flexiboy/Desktop/Projects/Research/code/master/core/Cooperation.o /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Cooperation.or /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Cooperation.od /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Cooperation.op: \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Cooperation.cc \
 ../core/Cooperation.h ../core/SolverTypes.h ../core/../mtl/IntTypes.h \
 ../core/../mtl/Alg.h ../core/../mtl/Vec.h ../core/../mtl/IntTypes.h \
 ../core/../mtl/XAlloc.h ../core/../mtl/Vec.h ../core/../mtl/Map.h \
 ../core/../mtl/Alloc.h ../core/Solver.h ../core/../mtl/Heap.h \
 ../core/../utils/Options.h ../core/../utils/../mtl/IntTypes.h \
 ../core/../utils/../mtl/Vec.h ../core/../utils/ParseUtils.h \
 ../mtl/Sort.h ../mtl/Vec.h
/Users/Flexiboy/Desktop/Projects/Research/code/master/core/Main.o /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Main.or /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Main.od /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Main.op: \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Main.cc \
 /usr/local/include/omp.h /usr/local/include/librdkafka/rdkafka.h \
 /usr/local/include/cppkafka/cppkafka.h \
 /usr/local/include/cppkafka/buffer.h \
 /usr/local/include/cppkafka/macros.h \
 /usr/local/include/cppkafka/exceptions.h \
 /usr/local/include/cppkafka/error.h \
 /usr/local/include/cppkafka/clonable_ptr.h \
 /usr/local/include/cppkafka/configuration.h \
 /usr/local/include/boost/optional.hpp \
 /usr/local/include/boost/optional/optional.hpp \
 /usr/local/include/boost/assert.hpp \
 /usr/local/include/boost/core/addressof.hpp \
 /usr/local/include/boost/config.hpp \
 /usr/local/include/boost/config/user.hpp \
 /usr/local/include/boost/config/detail/select_compiler_config.hpp \
 /usr/local/include/boost/config/compiler/gcc.hpp \
 /usr/local/include/boost/config/detail/select_stdlib_config.hpp \
 /usr/local/include/boost/config/stdlib/libstdcpp3.hpp \
 /usr/local/include/boost/config/detail/select_platform_config.hpp \
 /usr/local/include/boost/config/platform/macos.hpp \
 /usr/local/include/boost/config/detail/posix_features.hpp \
 /usr/local/include/boost/config/detail/suffix.hpp \
 /usr/local/include/boost/core/enable_if.hpp \
 /usr/local/include/boost/core/explicit_operator_bool.hpp \
 /usr/local/include/boost/config/workaround.hpp \
 /usr/local/include/boost/core/swap.hpp \
 /usr/local/include/boost/optional/bad_optional_access.hpp \
 /usr/local/include/boost/static_assert.hpp \
 /usr/local/include/boost/detail/workaround.hpp \
 /usr/local/include/boost/throw_exception.hpp \
 /usr/local/include/boost/exception/exception.hpp \
 /usr/local/include/boost/assert/source_location.hpp \
 /usr/local/include/boost/current_function.hpp \
 /usr/local/include/boost/cstdint.hpp /usr/local/include/boost/type.hpp \
 /usr/local/include/boost/type_traits/alignment_of.hpp \
 /usr/local/include/boost/type_traits/intrinsics.hpp \
 /usr/local/include/boost/type_traits/detail/config.hpp \
 /usr/local/include/boost/version.hpp \
 /usr/local/include/boost/type_traits/integral_constant.hpp \
 /usr/local/include/boost/type_traits/conditional.hpp \
 /usr/local/include/boost/type_traits/has_nothrow_constructor.hpp \
 /usr/local/include/boost/type_traits/is_default_constructible.hpp \
 /usr/local/include/boost/type_traits/is_complete.hpp \
 /usr/local/include/boost/type_traits/declval.hpp \
 /usr/local/include/boost/type_traits/add_rvalue_reference.hpp \
 /usr/local/include/boost/type_traits/is_void.hpp \
 /usr/local/include/boost/type_traits/is_reference.hpp \
 /usr/local/include/boost/type_traits/is_lvalue_reference.hpp \
 /usr/local/include/boost/type_traits/is_rvalue_reference.hpp \
 /usr/local/include/boost/type_traits/remove_reference.hpp \
 /usr/local/include/boost/type_traits/is_function.hpp \
 /usr/local/include/boost/type_traits/detail/is_function_cxx_11.hpp \
 /usr/local/include/boost/type_traits/detail/yes_no_type.hpp \
 /usr/local/include/boost/type_traits/type_with_alignment.hpp \
 /usr/local/include/boost/type_traits/is_pod.hpp \
 /usr/local/include/boost/type_traits/is_scalar.hpp \
 /usr/local/include/boost/type_traits/is_arithmetic.hpp \
 /usr/local/include/boost/type_traits/is_integral.hpp \
 /usr/local/include/boost/type_traits/is_floating_point.hpp \
 /usr/local/include/boost/type_traits/is_enum.hpp \
 /usr/local/include/boost/type_traits/is_pointer.hpp \
 /usr/local/include/boost/type_traits/is_member_pointer.hpp \
 /usr/local/include/boost/type_traits/is_member_function_pointer.hpp \
 /usr/local/include/boost/type_traits/detail/is_member_function_pointer_cxx_11.hpp \
 /usr/local/include/boost/type_traits/remove_const.hpp \
 /usr/local/include/boost/type_traits/decay.hpp \
 /usr/local/include/boost/type_traits/is_array.hpp \
 /usr/local/include/boost/type_traits/remove_bounds.hpp \
 /usr/local/include/boost/type_traits/remove_extent.hpp \
 /usr/local/include/boost/type_traits/add_pointer.hpp \
 /usr/local/include/boost/type_traits/remove_cv.hpp \
 /usr/local/include/boost/type_traits/is_base_of.hpp \
 /usr/local/include/boost/type_traits/is_base_and_derived.hpp \
 /usr/local/include/boost/type_traits/is_same.hpp \
 /usr/local/include/boost/type_traits/is_class.hpp \
 /usr/local/include/boost/type_traits/is_const.hpp \
 /usr/local/include/boost/type_traits/is_constructible.hpp \
 /usr/local/include/boost/type_traits/is_destructible.hpp \
 /usr/local/include/boost/type_traits/is_nothrow_move_assignable.hpp \
 /usr/local/include/boost/type_traits/has_trivial_move_assign.hpp \
 /usr/local/include/boost/type_traits/is_assignable.hpp \
 /usr/local/include/boost/type_traits/is_volatile.hpp \
 /usr/local/include/boost/type_traits/has_nothrow_assign.hpp \
 /usr/local/include/boost/type_traits/enable_if.hpp \
 /usr/local/include/boost/type_traits/is_nothrow_move_constructible.hpp \
 /usr/local/include/boost/move/utility.hpp \
 /usr/local/include/boost/move/detail/config_begin.hpp \
 /usr/local/include/boost/move/detail/workaround.hpp \
 /usr/local/include/boost/move/utility_core.hpp \
 /usr/local/include/boost/move/core.hpp \
 /usr/local/include/boost/move/detail/config_end.hpp \
 /usr/local/include/boost/move/detail/meta_utils.hpp \
 /usr/local/include/boost/move/detail/meta_utils_core.hpp \
 /usr/local/include/boost/move/traits.hpp \
 /usr/local/include/boost/move/detail/type_traits.hpp \
 /usr/local/include/boost/none.hpp /usr/local/include/boost/none_t.hpp \
 /usr/local/include/boost/utility/compare_pointees.hpp \
 /usr/local/include/boost/utility/result_of.hpp \
 /usr/local/include/boost/preprocessor/cat.hpp \
 /usr/local/include/boost/preprocessor/config/config.hpp \
 /usr/local/include/boost/preprocessor/iteration/iterate.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/dec.hpp \
 /usr/local/include/boost/preprocessor/config/limits.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/limits/dec_256.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/inc.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/limits/inc_256.hpp \
 /usr/local/include/boost/preprocessor/array/elem.hpp \
 /usr/local/include/boost/preprocessor/array/data.hpp \
 /usr/local/include/boost/preprocessor/tuple/elem.hpp \
 /usr/local/include/boost/preprocessor/facilities/expand.hpp \
 /usr/local/include/boost/preprocessor/facilities/overload.hpp \
 /usr/local/include/boost/preprocessor/variadic/size.hpp \
 /usr/local/include/boost/preprocessor/control/iif.hpp \
 /usr/local/include/boost/preprocessor/facilities/check_empty.hpp \
 /usr/local/include/boost/preprocessor/variadic/has_opt.hpp \
 /usr/local/include/boost/preprocessor/variadic/limits/size_64.hpp \
 /usr/local/include/boost/preprocessor/tuple/rem.hpp \
 /usr/local/include/boost/preprocessor/tuple/detail/is_single_return.hpp \
 /usr/local/include/boost/preprocessor/variadic/elem.hpp \
 /usr/local/include/boost/preprocessor/variadic/limits/elem_64.hpp \
 /usr/local/include/boost/preprocessor/array/size.hpp \
 /usr/local/include/boost/preprocessor/slot/slot.hpp \
 /usr/local/include/boost/preprocessor/slot/detail/def.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_params.hpp \
 /usr/local/include/boost/preprocessor/punctuation/comma_if.hpp \
 /usr/local/include/boost/preprocessor/control/if.hpp \
 /usr/local/include/boost/preprocessor/logical/bool.hpp \
 /usr/local/include/boost/preprocessor/logical/limits/bool_256.hpp \
 /usr/local/include/boost/preprocessor/facilities/empty.hpp \
 /usr/local/include/boost/preprocessor/punctuation/comma.hpp \
 /usr/local/include/boost/preprocessor/repetition/repeat.hpp \
 /usr/local/include/boost/preprocessor/debug/error.hpp \
 /usr/local/include/boost/preprocessor/detail/auto_rec.hpp \
 /usr/local/include/boost/preprocessor/detail/limits/auto_rec_256.hpp \
 /usr/local/include/boost/preprocessor/tuple/eat.hpp \
 /usr/local/include/boost/preprocessor/repetition/limits/repeat_256.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_trailing_params.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_binary_params.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum_shifted_params.hpp \
 /usr/local/include/boost/preprocessor/facilities/intercept.hpp \
 /usr/local/include/boost/preprocessor/facilities/limits/intercept_256.hpp \
 /usr/local/include/boost/type_traits/type_identity.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/iter/forward1.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/bounds/lower1.hpp \
 /usr/local/include/boost/preprocessor/slot/detail/shared.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/bounds/upper1.hpp \
 /usr/local/include/boost/preprocessor/iteration/detail/iter/limits/forward1_256.hpp \
 /usr/local/include/boost/utility/detail/result_of_iterate.hpp \
 /usr/local/include/boost/optional/optional_fwd.hpp \
 /usr/local/include/boost/optional/detail/optional_config.hpp \
 /usr/local/include/boost/optional/detail/optional_factory_support.hpp \
 /usr/local/include/boost/optional/detail/optional_aligned_storage.hpp \
 /usr/local/include/boost/optional/detail/optional_trivially_copyable_base.hpp \
 /usr/local/include/boost/optional/detail/optional_reference_spec.hpp \
 /usr/local/include/boost/optional/detail/optional_relops.hpp \
 /usr/local/include/boost/optional/detail/optional_swap.hpp \
 /usr/local/include/cppkafka/topic_partition_list.h \
 /usr/local/include/cppkafka/topic_configuration.h \
 /usr/local/include/cppkafka/clonable_ptr.h \
 /usr/local/include/cppkafka/configuration_base.h \
 /usr/local/include/cppkafka/configuration_option.h \
 /usr/local/include/cppkafka/event.h \
 /usr/local/include/cppkafka/message.h \
 /usr/local/include/cppkafka/buffer.h \
 /usr/local/include/cppkafka/header_list.h \
 /usr/local/include/cppkafka/header.h \
 /usr/local/include/cppkafka/header_list_iterator.h \
 /usr/local/include/cppkafka/message_timestamp.h \
 /usr/local/include/cppkafka/topic_partition.h \
 /usr/local/include/cppkafka/configuration_base.h \
 /usr/local/include/cppkafka/configuration_option.h \
 /usr/local/include/cppkafka/consumer.h \
 /usr/local/include/cppkafka/kafka_handle_base.h \
 /usr/local/include/cppkafka/group_information.h \
 /usr/local/include/cppkafka/metadata.h \
 /usr/local/include/cppkafka/configuration.h \
 /usr/local/include/cppkafka/logging.h \
 /usr/local/include/cppkafka/queue.h \
 /usr/local/include/cppkafka/detail/callback_invoker.h \
 /usr/local/include/cppkafka/detail/../logging.h \
 /usr/local/include/cppkafka/detail/../kafka_handle_base.h \
 /usr/local/include/cppkafka/error.h /usr/local/include/cppkafka/event.h \
 /usr/local/include/cppkafka/exceptions.h \
 /usr/local/include/cppkafka/group_information.h \
 /usr/local/include/cppkafka/header.h \
 /usr/local/include/cppkafka/header_list.h \
 /usr/local/include/cppkafka/header_list_iterator.h \
 /usr/local/include/cppkafka/kafka_handle_base.h \
 /usr/local/include/cppkafka/logging.h \
 /usr/local/include/cppkafka/macros.h \
 /usr/local/include/cppkafka/message.h \
 /usr/local/include/cppkafka/message_builder.h \
 /usr/local/include/cppkafka/topic.h \
 /usr/local/include/cppkafka/message_internal.h \
 /usr/local/include/cppkafka/message_timestamp.h \
 /usr/local/include/cppkafka/metadata.h \
 /usr/local/include/cppkafka/producer.h \
 /usr/local/include/cppkafka/message_builder.h \
 /usr/local/include/cppkafka/queue.h /usr/local/include/cppkafka/topic.h \
 /usr/local/include/cppkafka/topic_configuration.h \
 /usr/local/include/cppkafka/topic_partition.h \
 /usr/local/include/cppkafka/topic_partition_list.h \
 /usr/local/include/cppkafka/utils/backoff_committer.h \
 /usr/local/include/cppkafka/utils/../consumer.h \
 /usr/local/include/cppkafka/utils/backoff_performer.h \
 /usr/local/include/cppkafka/utils/../exceptions.h \
 /usr/local/include/cppkafka/utils/../detail/callback_invoker.h \
 /usr/local/include/cppkafka/utils/../macros.h \
 /usr/local/include/cppkafka/utils/backoff_performer.h \
 /usr/local/include/cppkafka/utils/buffered_producer.h \
 /usr/local/include/cppkafka/utils/../producer.h \
 /usr/local/include/cppkafka/utils/../message_internal.h \
 /usr/local/include/cppkafka/utils/compacted_topic_processor.h \
 /usr/local/include/cppkafka/utils/../buffer.h \
 /usr/local/include/cppkafka/utils/consumer_dispatcher.h \
 /usr/local/include/cppkafka/utils/poll_interface.h \
 /usr/local/include/cppkafka/utils/poll_strategy_base.h \
 /usr/local/include/boost/any.hpp /usr/local/include/boost/type_index.hpp \
 /usr/local/include/boost/type_index/stl_type_index.hpp \
 /usr/local/include/boost/type_index/type_index_facade.hpp \
 /usr/local/include/boost/container_hash/hash_fwd.hpp \
 /usr/local/include/boost/core/demangle.hpp \
 /usr/local/include/boost/type_traits/add_reference.hpp \
 /usr/local/include/boost/utility/enable_if.hpp \
 /usr/local/include/cppkafka/utils/../queue.h \
 /usr/local/include/cppkafka/utils/../event.h \
 /usr/local/include/cppkafka/utils/../macros.h \
 /usr/local/include/cppkafka/utils/../message.h \
 /usr/local/include/cppkafka/utils/../topic_partition_list.h \
 /usr/local/include/cppkafka/utils/poll_interface.h \
 /usr/local/include/cppkafka/utils/roundrobin_poll_strategy.h \
 /usr/local/include/cppkafka/utils/poll_strategy_base.h \
 /usr/local/include/boost/program_options.hpp \
 /usr/local/include/boost/program_options/options_description.hpp \
 /usr/local/include/boost/program_options/config.hpp \
 /usr/local/include/boost/config/auto_link.hpp \
 /usr/local/include/boost/program_options/errors.hpp \
 /usr/local/include/boost/program_options/value_semantic.hpp \
 /usr/local/include/boost/function/function1.hpp \
 /usr/local/include/boost/function/detail/maybe_include.hpp \
 /usr/local/include/boost/function/function_template.hpp \
 /usr/local/include/boost/function/detail/prologue.hpp \
 /usr/local/include/boost/config/no_tr1/functional.hpp \
 /usr/local/include/boost/function/function_base.hpp \
 /usr/local/include/boost/integer.hpp \
 /usr/local/include/boost/integer_fwd.hpp \
 /usr/local/include/boost/limits.hpp \
 /usr/local/include/boost/integer_traits.hpp \
 /usr/local/include/boost/type_traits/has_trivial_copy.hpp \
 /usr/local/include/boost/type_traits/is_copy_constructible.hpp \
 /usr/local/include/boost/type_traits/has_trivial_destructor.hpp \
 /usr/local/include/boost/type_traits/composite_traits.hpp \
 /usr/local/include/boost/type_traits/is_union.hpp \
 /usr/local/include/boost/ref.hpp /usr/local/include/boost/core/ref.hpp \
 /usr/local/include/boost/function_equal.hpp \
 /usr/local/include/boost/function/function_fwd.hpp \
 /usr/local/include/boost/mem_fn.hpp \
 /usr/local/include/boost/bind/mem_fn.hpp \
 /usr/local/include/boost/get_pointer.hpp \
 /usr/local/include/boost/config/no_tr1/memory.hpp \
 /usr/local/include/boost/bind/mem_fn_template.hpp \
 /usr/local/include/boost/bind/mem_fn_cc.hpp \
 /usr/local/include/boost/preprocessor/enum.hpp \
 /usr/local/include/boost/preprocessor/repetition/enum.hpp \
 /usr/local/include/boost/preprocessor/enum_params.hpp \
 /usr/local/include/boost/preprocessor/repeat.hpp \
 /usr/local/include/boost/preprocessor/inc.hpp \
 /usr/local/include/boost/core/no_exceptions_support.hpp \
 /usr/local/include/boost/lexical_cast.hpp \
 /usr/local/include/boost/range/iterator_range_core.hpp \
 /usr/local/include/boost/iterator/iterator_traits.hpp \
 /usr/local/include/boost/iterator/iterator_facade.hpp \
 /usr/local/include/boost/iterator/interoperable.hpp \
 /usr/local/include/boost/mpl/bool.hpp \
 /usr/local/include/boost/mpl/bool_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/adl_barrier.hpp \
 /usr/local/include/boost/mpl/aux_/config/adl.hpp \
 /usr/local/include/boost/mpl/aux_/config/msvc.hpp \
 /usr/local/include/boost/mpl/aux_/config/intel.hpp \
 /usr/local/include/boost/mpl/aux_/config/gcc.hpp \
 /usr/local/include/boost/mpl/aux_/config/workaround.hpp \
 /usr/local/include/boost/mpl/integral_c_tag.hpp \
 /usr/local/include/boost/mpl/aux_/config/static_constant.hpp \
 /usr/local/include/boost/mpl/or.hpp \
 /usr/local/include/boost/mpl/aux_/config/use_preprocessed.hpp \
 /usr/local/include/boost/mpl/aux_/nested_type_wknd.hpp \
 /usr/local/include/boost/mpl/aux_/na_spec.hpp \
 /usr/local/include/boost/mpl/lambda_fwd.hpp \
 /usr/local/include/boost/mpl/void_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/na.hpp \
 /usr/local/include/boost/mpl/aux_/na_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/config/ctps.hpp \
 /usr/local/include/boost/mpl/aux_/config/lambda.hpp \
 /usr/local/include/boost/mpl/aux_/config/ttp.hpp \
 /usr/local/include/boost/mpl/int.hpp \
 /usr/local/include/boost/mpl/int_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/nttp_decl.hpp \
 /usr/local/include/boost/mpl/aux_/config/nttp.hpp \
 /usr/local/include/boost/mpl/aux_/integral_wrapper.hpp \
 /usr/local/include/boost/mpl/aux_/static_cast.hpp \
 /usr/local/include/boost/mpl/aux_/lambda_arity_param.hpp \
 /usr/local/include/boost/mpl/aux_/template_arity_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/arity.hpp \
 /usr/local/include/boost/mpl/aux_/config/dtp.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessor/params.hpp \
 /usr/local/include/boost/mpl/aux_/config/preprocessor.hpp \
 /usr/local/include/boost/preprocessor/comma_if.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessor/enum.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessor/def_params_tail.hpp \
 /usr/local/include/boost/mpl/limits/arity.hpp \
 /usr/local/include/boost/preprocessor/logical/and.hpp \
 /usr/local/include/boost/preprocessor/logical/bitand.hpp \
 /usr/local/include/boost/preprocessor/identity.hpp \
 /usr/local/include/boost/preprocessor/facilities/identity.hpp \
 /usr/local/include/boost/preprocessor/empty.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/add.hpp \
 /usr/local/include/boost/preprocessor/control/while.hpp \
 /usr/local/include/boost/preprocessor/list/fold_left.hpp \
 /usr/local/include/boost/preprocessor/list/detail/fold_left.hpp \
 /usr/local/include/boost/preprocessor/control/expr_iif.hpp \
 /usr/local/include/boost/preprocessor/list/adt.hpp \
 /usr/local/include/boost/preprocessor/detail/is_binary.hpp \
 /usr/local/include/boost/preprocessor/detail/check.hpp \
 /usr/local/include/boost/preprocessor/logical/compl.hpp \
 /usr/local/include/boost/preprocessor/list/detail/limits/fold_left_256.hpp \
 /usr/local/include/boost/preprocessor/list/limits/fold_left_256.hpp \
 /usr/local/include/boost/preprocessor/list/fold_right.hpp \
 /usr/local/include/boost/preprocessor/list/detail/fold_right.hpp \
 /usr/local/include/boost/preprocessor/list/reverse.hpp \
 /usr/local/include/boost/preprocessor/list/detail/limits/fold_right_256.hpp \
 /usr/local/include/boost/preprocessor/control/detail/while.hpp \
 /usr/local/include/boost/preprocessor/control/detail/limits/while_256.hpp \
 /usr/local/include/boost/preprocessor/control/limits/while_256.hpp \
 /usr/local/include/boost/preprocessor/logical/bitor.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/detail/is_maximum_number.hpp \
 /usr/local/include/boost/preprocessor/comparison/equal.hpp \
 /usr/local/include/boost/preprocessor/comparison/not_equal.hpp \
 /usr/local/include/boost/preprocessor/comparison/limits/not_equal_256.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/detail/maximum_number.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/detail/is_minimum_number.hpp \
 /usr/local/include/boost/preprocessor/logical/not.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/sub.hpp \
 /usr/local/include/boost/mpl/aux_/config/eti.hpp \
 /usr/local/include/boost/mpl/aux_/config/overload_resolution.hpp \
 /usr/local/include/boost/mpl/aux_/lambda_support.hpp \
 /usr/local/include/boost/mpl/aux_/include_preprocessed.hpp \
 /usr/local/include/boost/mpl/aux_/config/compiler.hpp \
 /usr/local/include/boost/preprocessor/stringize.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/or.hpp \
 /usr/local/include/boost/type_traits/is_convertible.hpp \
 /usr/local/include/boost/type_traits/is_abstract.hpp \
 /usr/local/include/boost/type_traits/add_lvalue_reference.hpp \
 /usr/local/include/boost/iterator/detail/config_def.hpp \
 /usr/local/include/boost/iterator/detail/config_undef.hpp \
 /usr/local/include/boost/iterator/iterator_categories.hpp \
 /usr/local/include/boost/mpl/eval_if.hpp \
 /usr/local/include/boost/mpl/if.hpp \
 /usr/local/include/boost/mpl/aux_/value_wknd.hpp \
 /usr/local/include/boost/mpl/aux_/config/integral.hpp \
 /usr/local/include/boost/mpl/identity.hpp \
 /usr/local/include/boost/mpl/placeholders.hpp \
 /usr/local/include/boost/mpl/arg.hpp \
 /usr/local/include/boost/mpl/arg_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/na_assert.hpp \
 /usr/local/include/boost/mpl/assert.hpp \
 /usr/local/include/boost/mpl/not.hpp \
 /usr/local/include/boost/mpl/aux_/yes_no.hpp \
 /usr/local/include/boost/mpl/aux_/config/arrays.hpp \
 /usr/local/include/boost/mpl/aux_/config/gpu.hpp \
 /usr/local/include/boost/mpl/aux_/config/pp_counter.hpp \
 /usr/local/include/boost/mpl/aux_/arity_spec.hpp \
 /usr/local/include/boost/mpl/aux_/arg_typedef.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/arg.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp \
 /usr/local/include/boost/iterator/detail/facade_iterator_category.hpp \
 /usr/local/include/boost/core/use_default.hpp \
 /usr/local/include/boost/mpl/and.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/and.hpp \
 /usr/local/include/boost/detail/indirect_traits.hpp \
 /usr/local/include/boost/type_traits/remove_pointer.hpp \
 /usr/local/include/boost/detail/select_type.hpp \
 /usr/local/include/boost/iterator/detail/enable_if.hpp \
 /usr/local/include/boost/type_traits/add_const.hpp \
 /usr/local/include/boost/mpl/always.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessor/default_params.hpp \
 /usr/local/include/boost/mpl/apply.hpp \
 /usr/local/include/boost/mpl/apply_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/apply_fwd.hpp \
 /usr/local/include/boost/mpl/apply_wrap.hpp \
 /usr/local/include/boost/mpl/aux_/has_apply.hpp \
 /usr/local/include/boost/mpl/has_xxx.hpp \
 /usr/local/include/boost/mpl/aux_/type_wrapper.hpp \
 /usr/local/include/boost/mpl/aux_/config/has_xxx.hpp \
 /usr/local/include/boost/mpl/aux_/config/msvc_typename.hpp \
 /usr/local/include/boost/mpl/aux_/config/has_apply.hpp \
 /usr/local/include/boost/mpl/aux_/msvc_never_true.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/apply_wrap.hpp \
 /usr/local/include/boost/mpl/lambda.hpp \
 /usr/local/include/boost/mpl/bind.hpp \
 /usr/local/include/boost/mpl/bind_fwd.hpp \
 /usr/local/include/boost/mpl/aux_/config/bind.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/bind_fwd.hpp \
 /usr/local/include/boost/mpl/next.hpp \
 /usr/local/include/boost/mpl/next_prior.hpp \
 /usr/local/include/boost/mpl/aux_/common_name_wknd.hpp \
 /usr/local/include/boost/mpl/protect.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/bind.hpp \
 /usr/local/include/boost/mpl/aux_/full_lambda.hpp \
 /usr/local/include/boost/mpl/quote.hpp \
 /usr/local/include/boost/mpl/void.hpp \
 /usr/local/include/boost/mpl/aux_/has_type.hpp \
 /usr/local/include/boost/mpl/aux_/config/bcc.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/quote.hpp \
 /usr/local/include/boost/mpl/aux_/template_arity.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/template_arity.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/full_lambda.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/apply.hpp \
 /usr/local/include/boost/range/functions.hpp \
 /usr/local/include/boost/range/begin.hpp \
 /usr/local/include/boost/range/config.hpp \
 /usr/local/include/boost/range/iterator.hpp \
 /usr/local/include/boost/range/range_fwd.hpp \
 /usr/local/include/boost/range/mutable_iterator.hpp \
 /usr/local/include/boost/range/detail/extract_optional_type.hpp \
 /usr/local/include/boost/range/detail/msvc_has_iterator_workaround.hpp \
 /usr/local/include/boost/range/const_iterator.hpp \
 /usr/local/include/boost/range/end.hpp \
 /usr/local/include/boost/range/detail/implementation_help.hpp \
 /usr/local/include/boost/range/detail/common.hpp \
 /usr/local/include/boost/range/detail/sfinae.hpp \
 /usr/local/include/boost/range/size.hpp \
 /usr/local/include/boost/range/size_type.hpp \
 /usr/local/include/boost/range/difference_type.hpp \
 /usr/local/include/boost/range/has_range_iterator.hpp \
 /usr/local/include/boost/range/concepts.hpp \
 /usr/local/include/boost/concept_check.hpp \
 /usr/local/include/boost/concept/assert.hpp \
 /usr/local/include/boost/concept/detail/general.hpp \
 /usr/local/include/boost/concept/detail/backward_compatibility.hpp \
 /usr/local/include/boost/concept/detail/has_constraints.hpp \
 /usr/local/include/boost/type_traits/conversion_traits.hpp \
 /usr/local/include/boost/concept/usage.hpp \
 /usr/local/include/boost/concept/detail/concept_def.hpp \
 /usr/local/include/boost/preprocessor/seq/for_each_i.hpp \
 /usr/local/include/boost/preprocessor/repetition/for.hpp \
 /usr/local/include/boost/preprocessor/repetition/detail/for.hpp \
 /usr/local/include/boost/preprocessor/repetition/detail/limits/for_256.hpp \
 /usr/local/include/boost/preprocessor/repetition/limits/for_256.hpp \
 /usr/local/include/boost/preprocessor/seq/seq.hpp \
 /usr/local/include/boost/preprocessor/seq/elem.hpp \
 /usr/local/include/boost/preprocessor/seq/limits/elem_256.hpp \
 /usr/local/include/boost/preprocessor/seq/size.hpp \
 /usr/local/include/boost/preprocessor/seq/limits/size_256.hpp \
 /usr/local/include/boost/preprocessor/seq/detail/is_empty.hpp \
 /usr/local/include/boost/preprocessor/seq/enum.hpp \
 /usr/local/include/boost/preprocessor/seq/limits/enum_256.hpp \
 /usr/local/include/boost/concept/detail/concept_undef.hpp \
 /usr/local/include/boost/iterator/iterator_concepts.hpp \
 /usr/local/include/boost/range/value_type.hpp \
 /usr/local/include/boost/range/detail/misc_concept.hpp \
 /usr/local/include/boost/type_traits/make_unsigned.hpp \
 /usr/local/include/boost/type_traits/is_signed.hpp \
 /usr/local/include/boost/type_traits/is_unsigned.hpp \
 /usr/local/include/boost/type_traits/add_volatile.hpp \
 /usr/local/include/boost/range/detail/has_member_size.hpp \
 /usr/local/include/boost/utility.hpp \
 /usr/local/include/boost/utility/base_from_member.hpp \
 /usr/local/include/boost/preprocessor/repetition/repeat_from_to.hpp \
 /usr/local/include/boost/utility/binary.hpp \
 /usr/local/include/boost/preprocessor/control/deduce_d.hpp \
 /usr/local/include/boost/preprocessor/seq/cat.hpp \
 /usr/local/include/boost/preprocessor/seq/fold_left.hpp \
 /usr/local/include/boost/preprocessor/seq/limits/fold_left_256.hpp \
 /usr/local/include/boost/preprocessor/seq/transform.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/mod.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/detail/div_base.hpp \
 /usr/local/include/boost/preprocessor/comparison/less_equal.hpp \
 /usr/local/include/boost/preprocessor/arithmetic/detail/is_1_number.hpp \
 /usr/local/include/boost/utility/identity_type.hpp \
 /usr/local/include/boost/type_traits/function_traits.hpp \
 /usr/local/include/boost/core/checked_delete.hpp \
 /usr/local/include/boost/core/noncopyable.hpp \
 /usr/local/include/boost/range/distance.hpp \
 /usr/local/include/boost/iterator/distance.hpp \
 /usr/local/include/boost/range/empty.hpp \
 /usr/local/include/boost/range/rbegin.hpp \
 /usr/local/include/boost/range/reverse_iterator.hpp \
 /usr/local/include/boost/iterator/reverse_iterator.hpp \
 /usr/local/include/boost/iterator/iterator_adaptor.hpp \
 /usr/local/include/boost/range/rend.hpp \
 /usr/local/include/boost/range/algorithm/equal.hpp \
 /usr/local/include/boost/range/detail/safe_bool.hpp \
 /usr/local/include/boost/next_prior.hpp \
 /usr/local/include/boost/type_traits/has_plus.hpp \
 /usr/local/include/boost/type_traits/detail/has_binary_operator.hpp \
 /usr/local/include/boost/type_traits/has_plus_assign.hpp \
 /usr/local/include/boost/type_traits/has_minus.hpp \
 /usr/local/include/boost/type_traits/has_minus_assign.hpp \
 /usr/local/include/boost/iterator/advance.hpp \
 /usr/local/include/boost/lexical_cast/bad_lexical_cast.hpp \
 /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp \
 /usr/local/include/boost/lexical_cast/detail/is_character.hpp \
 /usr/local/include/boost/lexical_cast/detail/converter_numeric.hpp \
 /usr/local/include/boost/type_traits/is_float.hpp \
 /usr/local/include/boost/numeric/conversion/cast.hpp \
 /usr/local/include/boost/numeric/conversion/converter.hpp \
 /usr/local/include/boost/numeric/conversion/conversion_traits.hpp \
 /usr/local/include/boost/numeric/conversion/detail/conversion_traits.hpp \
 /usr/local/include/boost/numeric/conversion/detail/meta.hpp \
 /usr/local/include/boost/mpl/equal_to.hpp \
 /usr/local/include/boost/mpl/aux_/comparison_op.hpp \
 /usr/local/include/boost/mpl/aux_/numeric_op.hpp \
 /usr/local/include/boost/mpl/numeric_cast.hpp \
 /usr/local/include/boost/mpl/tag.hpp \
 /usr/local/include/boost/mpl/aux_/has_tag.hpp \
 /usr/local/include/boost/mpl/aux_/numeric_cast_utils.hpp \
 /usr/local/include/boost/mpl/aux_/config/forwarding.hpp \
 /usr/local/include/boost/mpl/aux_/msvc_eti_base.hpp \
 /usr/local/include/boost/mpl/aux_/is_msvc_eti_arg.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/equal_to.hpp \
 /usr/local/include/boost/numeric/conversion/detail/int_float_mixture.hpp \
 /usr/local/include/boost/numeric/conversion/int_float_mixture_enum.hpp \
 /usr/local/include/boost/mpl/integral_c.hpp \
 /usr/local/include/boost/mpl/integral_c_fwd.hpp \
 /usr/local/include/boost/numeric/conversion/detail/sign_mixture.hpp \
 /usr/local/include/boost/numeric/conversion/sign_mixture_enum.hpp \
 /usr/local/include/boost/numeric/conversion/detail/udt_builtin_mixture.hpp \
 /usr/local/include/boost/numeric/conversion/udt_builtin_mixture_enum.hpp \
 /usr/local/include/boost/numeric/conversion/detail/is_subranged.hpp \
 /usr/local/include/boost/mpl/multiplies.hpp \
 /usr/local/include/boost/mpl/times.hpp \
 /usr/local/include/boost/mpl/aux_/arithmetic_op.hpp \
 /usr/local/include/boost/mpl/aux_/largest_int.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/times.hpp \
 /usr/local/include/boost/mpl/less.hpp \
 /usr/local/include/boost/mpl/aux_/preprocessed/gcc/less.hpp \
 /usr/local/include/boost/numeric/conversion/converter_policies.hpp \
 /usr/local/include/boost/config/no_tr1/cmath.hpp \
 /usr/local/include/boost/numeric/conversion/detail/converter.hpp \
 /usr/local/include/boost/numeric/conversion/bounds.hpp \
 /usr/local/include/boost/numeric/conversion/detail/bounds.hpp \
 /usr/local/include/boost/numeric/conversion/numeric_cast_traits.hpp \
 /usr/local/include/boost/numeric/conversion/detail/numeric_cast_traits.hpp \
 /usr/local/include/boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_common.hpp \
 /usr/local/include/boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_long_long.hpp \
 /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp \
 /usr/local/include/boost/type_traits/has_left_shift.hpp \
 /usr/local/include/boost/type_traits/has_right_shift.hpp \
 /usr/local/include/boost/detail/lcast_precision.hpp \
 /usr/local/include/boost/lexical_cast/detail/widest_char.hpp \
 /usr/local/include/boost/array.hpp /usr/local/include/boost/swap.hpp \
 /usr/local/include/boost/container/container_fwd.hpp \
 /usr/local/include/boost/container/detail/std_fwd.hpp \
 /usr/local/include/boost/move/detail/std_ns_begin.hpp \
 /usr/local/include/boost/move/detail/std_ns_end.hpp \
 /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp \
 /usr/local/include/boost/lexical_cast/detail/lcast_char_constants.hpp \
 /usr/local/include/boost/lexical_cast/detail/lcast_unsigned_converters.hpp \
 /usr/local/include/boost/noncopyable.hpp \
 /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp \
 /usr/local/include/boost/core/cmath.hpp \
 /usr/local/include/boost/detail/basic_pointerbuf.hpp \
 /usr/local/include/boost/program_options/detail/value_semantic.hpp \
 /usr/local/include/boost/function.hpp \
 /usr/local/include/boost/preprocessor/iterate.hpp \
 /usr/local/include/boost/function/detail/function_iterate.hpp \
 /usr/local/include/boost/shared_ptr.hpp \
 /usr/local/include/boost/smart_ptr/shared_ptr.hpp \
 /usr/local/include/boost/smart_ptr/detail/shared_count.hpp \
 /usr/local/include/boost/smart_ptr/bad_weak_ptr.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_counted_base.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_has_gcc_intrinsics.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_has_sync_intrinsics.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_typeinfo_.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_counted_impl.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_noexcept.hpp \
 /usr/local/include/boost/checked_delete.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_disable_deprecated.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_convertible.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_nullptr_t.hpp \
 /usr/local/include/boost/smart_ptr/detail/spinlock_pool.hpp \
 /usr/local/include/boost/smart_ptr/detail/spinlock.hpp \
 /usr/local/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp \
 /usr/local/include/boost/smart_ptr/detail/yield_k.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_thread_pause.hpp \
 /usr/local/include/boost/smart_ptr/detail/sp_thread_sleep.hpp \
 /usr/local/include/boost/config/pragma_message.hpp \
 /usr/local/include/boost/smart_ptr/detail/operator_bool.hpp \
 /usr/local/include/boost/smart_ptr/detail/local_sp_deleter.hpp \
 /usr/local/include/boost/smart_ptr/detail/local_counted_base.hpp \
 /usr/local/include/boost/program_options/positional_options.hpp \
 /usr/local/include/boost/program_options/parsers.hpp \
 /usr/local/include/boost/program_options/option.hpp \
 /usr/local/include/boost/program_options/detail/cmdline.hpp \
 /usr/local/include/boost/program_options/cmdline.hpp \
 /usr/local/include/boost/program_options/detail/parsers.hpp \
 /usr/local/include/boost/program_options/detail/convert.hpp \
 /usr/local/include/boost/program_options/variables_map.hpp \
 /usr/local/include/boost/program_options/version.hpp \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/System.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/ParseUtils.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/Options.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/../mtl/Vec.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/../mtl/XAlloc.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../utils/ParseUtils.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Dimacs.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Cooperation.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/SolverTypes.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/Alg.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/Vec.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/Vec.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/Map.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/IntTypes.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/Alloc.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/XAlloc.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Solver.h \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/../mtl/Heap.h
/Users/Flexiboy/Desktop/Projects/Research/code/master/core/Solver.o /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Solver.or /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Solver.od /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Solver.op: \
 /Users/Flexiboy/Desktop/Projects/Research/code/master/core/Solver.cc \
 /usr/local/include/omp.h ../mtl/Sort.h ../mtl/Vec.h ../mtl/IntTypes.h \
 ../mtl/XAlloc.h ../core/Solver.h ../core/../mtl/Vec.h \
 ../core/../mtl/Heap.h ../core/../mtl/Vec.h ../core/../mtl/Alg.h \
 ../core/../utils/Options.h ../core/../utils/../mtl/IntTypes.h \
 ../core/../utils/../mtl/Vec.h ../core/../utils/ParseUtils.h \
 ../core/SolverTypes.h ../core/../mtl/IntTypes.h ../core/../mtl/Map.h \
 ../core/../mtl/IntTypes.h ../core/../mtl/Alloc.h ../core/../mtl/XAlloc.h \
 ../core/Cooperation.h ../core/Solver.h
