FROM ubuntu:20.10

WORKDIR /Users/Flexiboy/Desktop/Projects/Research/code/master

COPY master ./

RUN apt-get update -y\
	&& apt-get upgrade -y\
	&& apt-get install build-essential -y\
	&& apt-get install manpages-dev -y\
	&& apt-get install software-properties-common -y\
	&& add-apt-repository ppa:ubuntu-toolchain-r/test\
	&& apt-get update -y\
	&& apt-get upgrade -y\
	&& apt-get install libz-dev -y\
	&& apt-get install gcc -y\
	&& apt-get install g++-10 -y\
	&& apt-get install cmake -y\
	&& apt-get install librdkafka-dev -y\
	&& apt-get install libboost-all-dev -y\
	&& apt-get install git -y\
	&& apt-get install openssl -y\
	&& apt-get install libssl-dev -y\
	&& git clone https://github.com/mfontanini/cppkafka.git\
	&& cd cppkafka\
	&& mkdir build\
	&& cd build\
	&& cmake ..\
	&& make\
	&& make install\
	&& ldconfig\
	&& apt-get clean -y

WORKDIR /Users/Flexiboy/Desktop/Projects/Research/code/master/core

RUN find /usr/ -name 'libcppkafka*'\
	&& make clean\
	&& make -k CXX=g++-10

CMD /usr/bin/bash