apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: schemaregistry
  name: schemaregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schemaregistry
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: schemaregistry
    spec:
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schemaregistry.dvrc.svc.cluster.local
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: zookeeper.dvrc.svc.cluster.local:2181
            - name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
              value: WARN
          image: s3.dvic.devinci.fr/clusterspeed/schemaregistry:latest
          name: schemaregistry
          ports:
            - containerPort: 8081
          resources: {}
      hostname: schemaregistry
      imagePullSecrets: 
        - name: regcred
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: schemaregistry
  name: schemaregistry
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: schemaregistry
status:
  loadBalancer: {}